from .empty import *
from .doorkey import *
from .multiroom import *
from .fetch import *
from .gotoobject import *
from .gotodoor import *
from .putnear import *
from .lockedroom import *
from .keycorridor import *
from .unlock import *
from .unlockpickup import *
from .blockedunlockpickup import *
from .playground import *
from .redbluedoors import *
from .obstructedmaze import *
from .memory import *
from .fourrooms import *
from .crossing import *
from .lavagap import *
from .dynamicobstacles import *
from .distshift import *
from .custom import *
from .Lwallonleft import *
from .invertedLwallonright import *
from .twoLwalls import *
from .vertwalltop1 import *
from .vertwalltop2 import *
from .vertwalltop3 import *
from .vertwalltop4 import *
from .vertwalltop5 import *
from .vertwalltop6 import *
from .vertwalltop7 import *
from .vertwallbottom1 import *
from .vertwallbottom2 import *
from .vertwallbottom3 import *
from .vertwallbottom4 import *
from .vertwallbottom5 import *
from .wallholecenter import *
